spring:
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: task
    password: 
  h2.console.enabled: true  sql:    init:      mode: always
  jpa:
    hibernate:      ddl-auto: none